// AUTO-GENERATED by the admin on save. Do not edit by hand.
/* eslint-disable */
import p0 from './pages/g/en/sample-runner.json';
import p1 from './pages/g/zh/sample-runner.json';
import p2 from './pages/p/en/getting-started.json';
import p3 from './pages/home/en.json';
import p4 from './pages/home/zh.json';
import p5 from './pages/t/en/action.json';

const files: Record<string, unknown> = {
  "game/en/sample-runner": p0,
  "game/zh/sample-runner": p1,
  "guide/en/getting-started": p2,
  "home/en/home": p3,
  "home/zh/home": p4,
  "tag/en/action": p5,
};

export default files;
